#---------------------------------------------------------------------
#  GitHub Action Basics
#---------------------------------------------------------------------
name: My-GitHubActions-Basics
on: 
  push:
    branches: 
      - main
jobs:
  job-1 :
    runs-on: ubuntu-latest
    steps:
    - name: Print hello 
      run : echo "hello World from job-1"
    - name: Multiline command
      run : |
        touch 1.txt
        ls -la
        
          - name:sleep
         run :sleep 3
  job-2 :
    runs-on: ubuntu-latest
    needs: [job-1]
    steps:
    - name: Print hello
      run : echo "hello World from job-2"
      
         - name:sleep
         run :sleep 3
