#---------------------------------------------------------------------
#  GitHub Action Basics
#---------------------------------------------------------------------
name: My-GitHubActions-Basics
env:
  MY_APPLICATION_NAME    : "MyApp"
  MY_DEPLOY_PACKAGE_NAME : "MyApp-version-${{ github.sha }}"
on: 
  push:
    branches: 
      - main
jobs:
  job-1 :
    runs-on: ubuntu-latest
    steps:
    - name: Print hello 
      run : echo "hello World from job-1"
    - name: multiline command
      run: |
        touch 1.txt
        ls -la
        echo "My Appication name is: ${{ env.MY_APP_NAME }}"
          - name:sleep
         run :sleep 3
  job-2 :
    runs-on: ubuntu-latest
    needs: [job-1]
    steps:
    - name: Print Name
      run : echo "hello World from job-2"
    - name: Print Name
      run : echo "My pakcage name is ${{ env.MY_PACKAGE_NAME }}"
      
         - name:sleep
         run :sleep 3
